# Generated by Django 4.2.2 on 2023-06-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
